language: java
jdk:
 - openjdk8
addons: 
  firefox: "43.0"
cache:
  directories:
  - .autoconf
  - $HOME/.m2
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
script: mvn clean install -q


